### ISSUE TITLE
Request for fork

### ISSUE THREAD

**Issue by rhukster** [Deester4x4jr/grav-plugin-import#4]
hey @Deester4x4jr, a request for Fork has been submitted to our Repo: https://github.com/getgrav/grav/issues/1191

This basically asks for the GPM version to be pointed to the forked version.  Are you continuing to maintain and support this plugin?

Cheers!

**Comment by Deester4x4jr** [comment]
Hey @rhukster long time!

Honestly, I would like to continue to support this, but I do not have the time at the moment.  Please feel free to point the GPM at the forked version. He has done a bunch with it already.

Thanks!

-Josh-
